name: Continuous Integration

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: thumbv6m-none-eabi
          override: true
          
      - name: flip-link
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: flip-link

      - name: cargo build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
